//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Apartamento_Predio", "Predio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Verano.Models.Predio), "Apartamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Apartamento), true)]
[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Morador_Apartamento", "Apartamento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Verano.Models.Apartamento), "Morador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Morador), true)]
[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Resposta_Morador", "Morador", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Verano.Models.Morador), "Resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Resposta), true)]
[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Opcao_Pergunta", "Pergunta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Verano.Models.Pergunta), "Opcao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Opcao), true)]
[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Resposta_Opcao", "Opcao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Verano.Models.Opcao), "Resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Resposta), true)]
[assembly: EdmRelationshipAttribute("VeranoModel", "FK_Resposta_Pergunta", "Pergunta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Verano.Models.Pergunta), "Resposta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Verano.Models.Resposta), true)]

#endregion

namespace Verano.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VeranoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VeranoEntities object using the connection string found in the 'VeranoEntities' section of the application configuration file.
        /// </summary>
        public VeranoEntities() : base("name=VeranoEntities", "VeranoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VeranoEntities object.
        /// </summary>
        public VeranoEntities(string connectionString) : base(connectionString, "VeranoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VeranoEntities object.
        /// </summary>
        public VeranoEntities(EntityConnection connection) : base(connection, "VeranoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Apartamento> Apartamento
        {
            get
            {
                if ((_Apartamento == null))
                {
                    _Apartamento = base.CreateObjectSet<Apartamento>("Apartamento");
                }
                return _Apartamento;
            }
        }
        private ObjectSet<Apartamento> _Apartamento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Morador> Morador
        {
            get
            {
                if ((_Morador == null))
                {
                    _Morador = base.CreateObjectSet<Morador>("Morador");
                }
                return _Morador;
            }
        }
        private ObjectSet<Morador> _Morador;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predio> Predio
        {
            get
            {
                if ((_Predio == null))
                {
                    _Predio = base.CreateObjectSet<Predio>("Predio");
                }
                return _Predio;
            }
        }
        private ObjectSet<Predio> _Predio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Opcao> Opcao
        {
            get
            {
                if ((_Opcao == null))
                {
                    _Opcao = base.CreateObjectSet<Opcao>("Opcao");
                }
                return _Opcao;
            }
        }
        private ObjectSet<Opcao> _Opcao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pergunta> Pergunta
        {
            get
            {
                if ((_Pergunta == null))
                {
                    _Pergunta = base.CreateObjectSet<Pergunta>("Pergunta");
                }
                return _Pergunta;
            }
        }
        private ObjectSet<Pergunta> _Pergunta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Resposta> Resposta
        {
            get
            {
                if ((_Resposta == null))
                {
                    _Resposta = base.CreateObjectSet<Resposta>("Resposta");
                }
                return _Resposta;
            }
        }
        private ObjectSet<Resposta> _Resposta;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Apartamento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApartamento(Apartamento apartamento)
        {
            base.AddObject("Apartamento", apartamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Morador EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMorador(Morador morador)
        {
            base.AddObject("Morador", morador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredio(Predio predio)
        {
            base.AddObject("Predio", predio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Opcao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOpcao(Opcao opcao)
        {
            base.AddObject("Opcao", opcao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pergunta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPergunta(Pergunta pergunta)
        {
            base.AddObject("Pergunta", pergunta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resposta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResposta(Resposta resposta)
        {
            base.AddObject("Resposta", resposta);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Apartamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Apartamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Apartamento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idPredio">Initial value of the IdPredio property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="flagInadimplente">Initial value of the FlagInadimplente property.</param>
        public static Apartamento CreateApartamento(global::System.Int32 id, global::System.Int32 idPredio, global::System.Int32 numero, global::System.Boolean flagInadimplente)
        {
            Apartamento apartamento = new Apartamento();
            apartamento.Id = id;
            apartamento.IdPredio = idPredio;
            apartamento.Numero = numero;
            apartamento.FlagInadimplente = flagInadimplente;
            return apartamento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPredio
        {
            get
            {
                return _IdPredio;
            }
            set
            {
                OnIdPredioChanging(value);
                ReportPropertyChanging("IdPredio");
                _IdPredio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPredio");
                OnIdPredioChanged();
            }
        }
        private global::System.Int32 _IdPredio;
        partial void OnIdPredioChanging(global::System.Int32 value);
        partial void OnIdPredioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagInadimplente
        {
            get
            {
                return _FlagInadimplente;
            }
            set
            {
                OnFlagInadimplenteChanging(value);
                ReportPropertyChanging("FlagInadimplente");
                _FlagInadimplente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagInadimplente");
                OnFlagInadimplenteChanged();
            }
        }
        private global::System.Boolean _FlagInadimplente;
        partial void OnFlagInadimplenteChanging(global::System.Boolean value);
        partial void OnFlagInadimplenteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Apartamento_Predio", "Predio")]
        public Predio Predio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predio>("VeranoModel.FK_Apartamento_Predio", "Predio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predio>("VeranoModel.FK_Apartamento_Predio", "Predio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predio> PredioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predio>("VeranoModel.FK_Apartamento_Predio", "Predio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predio>("VeranoModel.FK_Apartamento_Predio", "Predio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Morador_Apartamento", "Morador")]
        public EntityCollection<Morador> Morador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Morador>("VeranoModel.FK_Morador_Apartamento", "Morador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Morador>("VeranoModel.FK_Morador_Apartamento", "Morador", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Morador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Morador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Morador object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        /// <param name="flagDisponivel">Initial value of the FlagDisponivel property.</param>
        /// <param name="flagConselheiro">Initial value of the FlagConselheiro property.</param>
        /// <param name="idApartamento">Initial value of the IdApartamento property.</param>
        /// <param name="flagDeficiente">Initial value of the FlagDeficiente property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="flagFumante">Initial value of the FlagFumante property.</param>
        /// <param name="flagProprietario">Initial value of the FlagProprietario property.</param>
        /// <param name="flagPraticaEsporte">Initial value of the FlagPraticaEsporte property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        public static Morador CreateMorador(global::System.Int32 id, global::System.String nome, global::System.String sobrenome, global::System.DateTime dataNascimento, global::System.DateTime dataCadastro, global::System.Boolean flagDisponivel, global::System.Boolean flagConselheiro, global::System.Int32 idApartamento, global::System.Boolean flagDeficiente, global::System.String email, global::System.Boolean flagFumante, global::System.Boolean flagProprietario, global::System.Boolean flagPraticaEsporte, global::System.String login)
        {
            Morador morador = new Morador();
            morador.Id = id;
            morador.Nome = nome;
            morador.Sobrenome = sobrenome;
            morador.DataNascimento = dataNascimento;
            morador.DataCadastro = dataCadastro;
            morador.FlagDisponivel = flagDisponivel;
            morador.FlagConselheiro = flagConselheiro;
            morador.IdApartamento = idApartamento;
            morador.FlagDeficiente = flagDeficiente;
            morador.Email = email;
            morador.FlagFumante = flagFumante;
            morador.FlagProprietario = flagProprietario;
            morador.FlagPraticaEsporte = flagPraticaEsporte;
            morador.Login = login;
            return morador;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cpf
        {
            get
            {
                return _Cpf;
            }
            set
            {
                OnCpfChanging(value);
                ReportPropertyChanging("Cpf");
                _Cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cpf");
                OnCpfChanged();
            }
        }
        private global::System.String _Cpf;
        partial void OnCpfChanging(global::System.String value);
        partial void OnCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagDisponivel
        {
            get
            {
                return _FlagDisponivel;
            }
            set
            {
                OnFlagDisponivelChanging(value);
                ReportPropertyChanging("FlagDisponivel");
                _FlagDisponivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagDisponivel");
                OnFlagDisponivelChanged();
            }
        }
        private global::System.Boolean _FlagDisponivel;
        partial void OnFlagDisponivelChanging(global::System.Boolean value);
        partial void OnFlagDisponivelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagConselheiro
        {
            get
            {
                return _FlagConselheiro;
            }
            set
            {
                OnFlagConselheiroChanging(value);
                ReportPropertyChanging("FlagConselheiro");
                _FlagConselheiro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagConselheiro");
                OnFlagConselheiroChanged();
            }
        }
        private global::System.Boolean _FlagConselheiro;
        partial void OnFlagConselheiroChanging(global::System.Boolean value);
        partial void OnFlagConselheiroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdApartamento
        {
            get
            {
                return _IdApartamento;
            }
            set
            {
                OnIdApartamentoChanging(value);
                ReportPropertyChanging("IdApartamento");
                _IdApartamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdApartamento");
                OnIdApartamentoChanged();
            }
        }
        private global::System.Int32 _IdApartamento;
        partial void OnIdApartamentoChanging(global::System.Int32 value);
        partial void OnIdApartamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagDeficiente
        {
            get
            {
                return _FlagDeficiente;
            }
            set
            {
                OnFlagDeficienteChanging(value);
                ReportPropertyChanging("FlagDeficiente");
                _FlagDeficiente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagDeficiente");
                OnFlagDeficienteChanged();
            }
        }
        private global::System.Boolean _FlagDeficiente;
        partial void OnFlagDeficienteChanging(global::System.Boolean value);
        partial void OnFlagDeficienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagFumante
        {
            get
            {
                return _FlagFumante;
            }
            set
            {
                OnFlagFumanteChanging(value);
                ReportPropertyChanging("FlagFumante");
                _FlagFumante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagFumante");
                OnFlagFumanteChanged();
            }
        }
        private global::System.Boolean _FlagFumante;
        partial void OnFlagFumanteChanging(global::System.Boolean value);
        partial void OnFlagFumanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagProprietario
        {
            get
            {
                return _FlagProprietario;
            }
            set
            {
                OnFlagProprietarioChanging(value);
                ReportPropertyChanging("FlagProprietario");
                _FlagProprietario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagProprietario");
                OnFlagProprietarioChanged();
            }
        }
        private global::System.Boolean _FlagProprietario;
        partial void OnFlagProprietarioChanging(global::System.Boolean value);
        partial void OnFlagProprietarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagPraticaEsporte
        {
            get
            {
                return _FlagPraticaEsporte;
            }
            set
            {
                OnFlagPraticaEsporteChanging(value);
                ReportPropertyChanging("FlagPraticaEsporte");
                _FlagPraticaEsporte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagPraticaEsporte");
                OnFlagPraticaEsporteChanged();
            }
        }
        private global::System.Boolean _FlagPraticaEsporte;
        partial void OnFlagPraticaEsporteChanging(global::System.Boolean value);
        partial void OnFlagPraticaEsporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Morador_Apartamento", "Apartamento")]
        public Apartamento Apartamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Apartamento>("VeranoModel.FK_Morador_Apartamento", "Apartamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Apartamento>("VeranoModel.FK_Morador_Apartamento", "Apartamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Apartamento> ApartamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Apartamento>("VeranoModel.FK_Morador_Apartamento", "Apartamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Apartamento>("VeranoModel.FK_Morador_Apartamento", "Apartamento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Morador", "Resposta")]
        public EntityCollection<Resposta> Resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Morador", "Resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Morador", "Resposta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Opcao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Opcao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Opcao object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="idPergunta">Initial value of the IdPergunta property.</param>
        /// <param name="flagObservacao">Initial value of the FlagObservacao property.</param>
        public static Opcao CreateOpcao(global::System.Int32 id, global::System.String titulo, global::System.Int32 idPergunta, global::System.Boolean flagObservacao)
        {
            Opcao opcao = new Opcao();
            opcao.Id = id;
            opcao.Titulo = titulo;
            opcao.IdPergunta = idPergunta;
            opcao.FlagObservacao = flagObservacao;
            return opcao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPergunta
        {
            get
            {
                return _IdPergunta;
            }
            set
            {
                OnIdPerguntaChanging(value);
                ReportPropertyChanging("IdPergunta");
                _IdPergunta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPergunta");
                OnIdPerguntaChanged();
            }
        }
        private global::System.Int32 _IdPergunta;
        partial void OnIdPerguntaChanging(global::System.Int32 value);
        partial void OnIdPerguntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagObservacao
        {
            get
            {
                return _FlagObservacao;
            }
            set
            {
                OnFlagObservacaoChanging(value);
                ReportPropertyChanging("FlagObservacao");
                _FlagObservacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagObservacao");
                OnFlagObservacaoChanged();
            }
        }
        private global::System.Boolean _FlagObservacao;
        partial void OnFlagObservacaoChanging(global::System.Boolean value);
        partial void OnFlagObservacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Opcao_Pergunta", "Pergunta")]
        public Pergunta Pergunta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Opcao_Pergunta", "Pergunta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Opcao_Pergunta", "Pergunta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pergunta> PerguntaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Opcao_Pergunta", "Pergunta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pergunta>("VeranoModel.FK_Opcao_Pergunta", "Pergunta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Opcao", "Resposta")]
        public EntityCollection<Resposta> Resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Opcao", "Resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Opcao", "Resposta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Pergunta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pergunta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pergunta object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static Pergunta CreatePergunta(global::System.Int32 id, global::System.String titulo, global::System.String tipo)
        {
            Pergunta pergunta = new Pergunta();
            pergunta.Id = id;
            pergunta.Titulo = titulo;
            pergunta.Tipo = tipo;
            return pergunta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Opcao_Pergunta", "Opcao")]
        public EntityCollection<Opcao> Opcao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Opcao>("VeranoModel.FK_Opcao_Pergunta", "Opcao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Opcao>("VeranoModel.FK_Opcao_Pergunta", "Opcao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Pergunta", "Resposta")]
        public EntityCollection<Resposta> Resposta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Pergunta", "Resposta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Resposta>("VeranoModel.FK_Resposta_Pergunta", "Resposta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Predio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predio object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Predio CreatePredio(global::System.Int32 id, global::System.String nome)
        {
            Predio predio = new Predio();
            predio.Id = id;
            predio.Nome = nome;
            return predio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Apartamento_Predio", "Apartamento")]
        public EntityCollection<Apartamento> Apartamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Apartamento>("VeranoModel.FK_Apartamento_Predio", "Apartamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Apartamento>("VeranoModel.FK_Apartamento_Predio", "Apartamento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VeranoModel", Name="Resposta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resposta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Resposta object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idMorador">Initial value of the IdMorador property.</param>
        /// <param name="idPergunta">Initial value of the IdPergunta property.</param>
        public static Resposta CreateResposta(global::System.Int32 id, global::System.Int32 idMorador, global::System.Int32 idPergunta)
        {
            Resposta resposta = new Resposta();
            resposta.Id = id;
            resposta.IdMorador = idMorador;
            resposta.IdPergunta = idPergunta;
            return resposta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMorador
        {
            get
            {
                return _IdMorador;
            }
            set
            {
                OnIdMoradorChanging(value);
                ReportPropertyChanging("IdMorador");
                _IdMorador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMorador");
                OnIdMoradorChanged();
            }
        }
        private global::System.Int32 _IdMorador;
        partial void OnIdMoradorChanging(global::System.Int32 value);
        partial void OnIdMoradorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPergunta
        {
            get
            {
                return _IdPergunta;
            }
            set
            {
                OnIdPerguntaChanging(value);
                ReportPropertyChanging("IdPergunta");
                _IdPergunta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPergunta");
                OnIdPerguntaChanged();
            }
        }
        private global::System.Int32 _IdPergunta;
        partial void OnIdPerguntaChanging(global::System.Int32 value);
        partial void OnIdPerguntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdOpcao
        {
            get
            {
                return _IdOpcao;
            }
            set
            {
                OnIdOpcaoChanging(value);
                ReportPropertyChanging("IdOpcao");
                _IdOpcao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdOpcao");
                OnIdOpcaoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdOpcao;
        partial void OnIdOpcaoChanging(Nullable<global::System.Int32> value);
        partial void OnIdOpcaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Morador", "Morador")]
        public Morador Morador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Morador>("VeranoModel.FK_Resposta_Morador", "Morador").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Morador>("VeranoModel.FK_Resposta_Morador", "Morador").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Morador> MoradorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Morador>("VeranoModel.FK_Resposta_Morador", "Morador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Morador>("VeranoModel.FK_Resposta_Morador", "Morador", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Opcao", "Opcao")]
        public Opcao Opcao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Opcao>("VeranoModel.FK_Resposta_Opcao", "Opcao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Opcao>("VeranoModel.FK_Resposta_Opcao", "Opcao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Opcao> OpcaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Opcao>("VeranoModel.FK_Resposta_Opcao", "Opcao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Opcao>("VeranoModel.FK_Resposta_Opcao", "Opcao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VeranoModel", "FK_Resposta_Pergunta", "Pergunta")]
        public Pergunta Pergunta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Resposta_Pergunta", "Pergunta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Resposta_Pergunta", "Pergunta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pergunta> PerguntaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pergunta>("VeranoModel.FK_Resposta_Pergunta", "Pergunta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pergunta>("VeranoModel.FK_Resposta_Pergunta", "Pergunta", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
